app_port: "8080"
postgres_dsn: "postgres://postgres:postgres@localhost:5433/task_manager?sslmode=disable"
redis_addr: "localhost:6379"
jwt_secret: "secret"
otel_enabled: false
otel_service_name: "task-manager-api"
otel_exporter_otlp_endpoint: "localhost:4317"
otel_exporter_otlp_insecure: true
smtp_host: "localhost"
smtp_port: 1025
smtp_username: ""
smtp_password: ""
smtp_from: "no-reply@task-manager.local"
worker_metrics_port: "9091"
